# Generated by Django 5.2.1 on 2025-06-02 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('identity', 'Identity Documents'), ('documents', 'Official Documents'), ('electronics', 'Electronics'), ('clothing', 'Clothing & Accessories'), ('personal_items', 'Personal Items'), ('transport', 'Transport Items'), ('pets', 'Pets'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=5)),
                ('location', models.CharField(choices=[('yaounde', 'Yaoundé'), ('douala', 'Douala'), ('garoua', 'Garoua'), ('maroua', 'Maroua'), ('ngoundere', 'Ngaoundéré'), ('bamenda', 'Bamenda'), ('buea', 'Buea'), ('bertoua', 'Bertoua'), ('bafoussam', 'Bafoussam'), ('ebolowa', 'Ebolowa'), ('other', 'Other')], max_length=100)),
                ('img', models.ImageField(upload_to='items/')),
                ('contact_info', models.CharField(max_length=100)),
                ('date_lost_or_found', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
