# Generated by Django 5.2.1 on 2025-06-14 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
