"""
Django settings for falla_proj project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'falla237.onrender.com', 'foudadev.site', 'www.foudadev.site']

CSRF_TRUSTED_ORIGINS = [
    'https://falla237.onrender.com', 
    'https://foudadev.site', 
    'https://www.foudadev.site', 
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    #Third party app
    'pwa',
    'django_recaptcha',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'falla_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'falla_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
     'default': dj_database_url.config(default=config('DATABASE_URL'))
    
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR ,'static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Optional: Enable compression (recommended)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'main.CustomUser'

# settings.py
DATA_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024  # 4MB



# reCAPTCHA settings
RECAPTCHA_PUBLIC_KEY = config('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = config('RECAPTCHA_PRIVATE_KEY')


# Cloudinary Configuration
cloudinary.config(
    cloud_name = config('CLOUDINARY_CLOUD_NAME'),
    api_key = config('CLOUDINARY_API_KEY'),
    api_secret = config('CLOUDINARY_API_SECRET'),
)



# PWA Settings
PWA_APP_NAME = "Falla237"
PWA_APP_SHORT_NAME = "Falla237"
PWA_APP_DESCRIPTION = "Lost and Found items platform for Cameroon"
PWA_APP_THEME_COLOR = "#0A0302"
PWA_APP_BACKGROUND_COLOR = "#ffffff"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_ORIENTATION = "any"
PWA_APP_START_URL = "/"
PWA_APP_STATUS_BAR_COLOR = "default"
PWA_APP_LANG = "en-US"
PWA_APP_DIR = "ltr"
PWA_APP_OFFLINE_PAGE = 'offline.html'

PWA_APP_ICONS = [
    {
        "src": "/static/images/icons/falla_48x48.png",
        "type": "image/png",
        "sizes": "48x48",
        "purpose": "any"
    },
    {
        "src": "/static/images/icons/falla_72x72.png",
        "type": "image/png",
        "sizes": "72x72",
        "purpose": "any"
    },
    {
        "src": "/static/images/icons/falla_96x96.png",
        "type": "image/png",
        "sizes": "96x96",
        "purpose": "any"
    },
    {
        "src": "/static/images/icons/falla_144x144.png",
        "type": "image/png",
        "sizes": "144x144",
        "purpose": "any"
    },
    {
        "src": "/static/images/icons/falla_192x192.png",
        "type": "image/png",
        "sizes": "192x192",
        "purpose": "any maskable"
    },
    {
        "src": "/static/images/icons/falla_512x512.png",
        "type": "image/png",
        "sizes": "512x512",
        "purpose": "any maskable"
    }
]

PWA_APP_ICONS_APPLE = [
    {
        "src": "/static/images/icons/falla_180x180.png",
        "sizes": "180x180",
        "type": "image/png"
    }
]

PWA_APP_SPLASH_SCREEN = [
    {
        "src": "/static/images/icons/falla_1024x1024.png",
        "media": "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
    }
]

PWA_APP_SCREENSHOTS = [
    {
        "src": "/static/images/icons/falla_screenshot_750x1334.png",
        "sizes": "750x1334",
        "type": "image/png",
        "form_factor": "narrow",
        "label": "Mobile View"
    },
    {
        "src": "/static/images/icons/falla_screenshot_720x1280.png",
        "sizes": "720x1280",
        "type": "image/png",
        "form_factor": "wide",
        "label": "Desktop View"
    }
]
